### ISSUE TITLE
Can`t install 2.2.2 x64 on windows 11

### ISSUE THREAD

**Issue by Ldes** [Thavarshan/comet#44]
- Comet Version: 2.2.2
- TypeScript Version: 5.3.3

### Description

When installing version v2.2.2 (x64) I get an error.

> A JavaScript error occurred in the main process
> Uncaught Exception:
> Error: Cannot find module 'fluent-ffmpeg'
> Require stack:
> - C:\Users\serej\AppData\Local\Comet\app-2.2.2\resources\app.asar\.vite\build\main.js
> at Module._resolveFilename (node:internal/modules/cjs/loader: 1232:15)
> at s._resolveFilename (node:electron/js2c/browser_init:2:123740)
> at Module._load (node:internal/modules/cjs/loader: 1058:27)
> at c._load (node:electron/js2c/node_init:2:16955)
> at Module.require (node:internal/modules/cjs/loader:1318:19) at require (node:internal/modules/helpers:179:18)
> at Module.<anonymous>
> (C:\Users\serej\AppData\Local\Comet\app-2.2.2\resources\app.asar\.vite\build\main.js:1:2...
> at Module._compile (node:internal/modules/cjs/loader: 1484:14)
> at Module._extensions..js (node:internal/modules/cjs/loader: 1564:10)
> at Module.load (node:internal/modules/cjs/loader: 1295:32)

### Steps To Reproduce
- Get setup from https://github.com/Thavarshan/comet/releases/download/v2.2.2/comet-2.2.2-x64-setup.exe
- Run setup
- Get error in install process

### Actual result
I get an error, the installation is interrupted

### Env

- OS Name:     Microsoft Windows 11 Pro
- OS Version:  10.0.22621 N/A Build 22621

### Attach

![Setup error](https://github.com/user-attachments/assets/e09ee3e9-523b-47e6-88cc-58a7f2abfb5c)

**Comment by Thavarshan** [comment]
Thank you for bringing this to my attention, and I apologise for any inconvenience this may have caused.

I’ve taken note of the concerns, and I’ll be looking into this to assess how to resolve it properly.

**Comment by Ldes** [comment]
I checked the installation of the previous version, 2.2.1 x64
The installation went smoothly, without errors.

**Comment by Thavarshan** [comment]
Thanks a lot! that was actually helpful. The dependency upgrades must have affected the unpacking process. I still need to figure out how to solve this though.

**Comment by Thavarshan** [comment]
Hi! Just wanted to update you. Working on a patch, will release soon!

**Comment by Thavarshan** [comment]
Latest release `v2.2.3` did not solve this issue unfortunately 😞

Still trying to figure out a fix.

**Comment by Thavarshan** [comment]
Can confirm issue has been fixed with the release `v2.2.3`.
